POST http://localhost:9080/register HTTP/1.1
content-Type: application/json

{
    "username": "rahul123",
    "password": "mypassword21",
    "email": "rahul@example.com",
    "name": "Rahul Pandey"
}

###

POST http://localhost:9080/login HTTP/1.1
content-Type: application/json

{
    "email": "arun@example.com",
    "password": "mypassword"
}

###
POST http://localhost:9080/login HTTP/1.1
content-Type: application/json

{
    "email": "rahul@example.com",
    "password": "mypassword21"
}

###

GET http://localhost:9080/get_user_and_profile
content-Type: application/json

{
    "token":"707be8283a791c760ae7c09bb1550bf8ef324d48c5f8588c9f1650da52f591e5"
}

###
POST http://localhost:9080/update_profile_data
content-Type: application/json

{
    "token":"fc1719dc7c70662e47c6839d3de35772d7a535553797566dbc074843b236fd11",
    "bio": "Hey I am Arun, I am from Delhi, I work in XYZ Company",
  "currentPost": "CTO",
  "pastWork": [
    {
        "company":"Microsoft",
        "position":"CTO",
        "years":"2+"
    }
  ],
  "education": [
    {
        "school":"RPVV",
        "degree":"B.Tech",
        "fieldOfStudy":"2015-2019"
    }
  ]
}

###
GET http://localhost:9080/user/get_all_users